version: '3'

services:
  es01:
    image: elasticsearch:7.4.1
    environment:
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes: 
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - data01:/usr/share/elasticsearch/data
      - certs:$CERTS_DIR
    ports:
      - 9200:9200
    healthcheck:
      test: curl --cacert $CERTS_DIR/ca/ca.crt -s https://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

  kibana:
    image: kibana:7.4.1
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
      - certs:$CERTS_DIR
    depends_on:
      - es01
    ports:
      - 5601:5601

volumes:
  data01:
  certs:
